export const GET_POSTS = "GET_POSTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY_TYPE = "GET_CATEGORY_TYPE";
export const GET_POST_BY_CATEGORY_TYPE = "GET_POST_BY_CATEGORY_TYPE"
