# Generated by Django 2.2.5 on 2019-09-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190921_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
