# Generated by Django 2.2.5 on 2019-10-04 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('SCIENCES', (('MATHS', 'Sciences Mathématiques'), ('PHY', 'Physique'), ('CHE', 'Chimie'), ('ASTR', 'Astronomie'), ('BIO', 'Biologie'), ('EART', 'Sciences de la Terre'), ('STATS', 'Statistiques'), ('CS', 'Code & Programmation'), ('DATA', 'Data Science & Machine Learning'), ('ALGO', 'Algorithme et Structure de dconnées'), ('AI', 'Intelligence Artificielle'), ('SECU', 'Sécurité Informatique')))], max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
